#!/usr/bin/env bash
# Display-profile switcher behind the SketchyBar dropdown.
#   display.sh save   <name>   capture the current arrangement as profile <name>
#   display.sh apply  <name>   replay a saved arrangement, then re-tile AeroSpace
#   display.sh sync            re-apply the current profile's sizing (after
#                              editing sizes.sh) without touching the displays
#   display.sh update          refresh the widget label from saved state (plugin)
#
# Profiles are saved displayplacer command lines in:
#   ~/.config/sketchybar/profiles/<name>.displayplacer
# The active profile name is remembered in:
#   ~/.config/sketchybar/profiles/.current
#
# Applying a profile also re-sizes the bar: sizes.sh maps the profile to a
# sizing preset (the displays in each arrangement differ in density by more than
# 2x, and SketchyBar has only one global bar), so apply reloads SketchyBar and
# rewrites AeroSpace's top gap to match the new bar height.
# Full path to brew bins — SketchyBar runs with a minimal GUI PATH.
export PATH="/opt/homebrew/bin:$PATH"
source "$HOME/.config/sketchybar/colors.sh"

PROFILE_DIR="$HOME/.config/sketchybar/profiles"
STATE="$PROFILE_DIR/.current"
mkdir -p "$PROFILE_DIR"

action="$1"
name="$2"

# Keep AeroSpace's top gap in step with the active preset's bar height. The
# outer.top line in ~/.aerospace.toml is generated — edit AERO_GAP in sizes.sh,
# not the toml.
sync_gaps() {
  local toml="$HOME/.aerospace.toml"
  [ -f "$toml" ] || return 0

  source "$HOME/.config/sketchybar/sizes.sh"
  local repl="outer.top = [{ monitor.'built-in' = $AERO_TOP_BUILTIN }, $AERO_TOP_EXTERNAL]  # generated by display.sh"

  awk -v repl="$repl" '
    /^outer\.top = .*# generated by display\.sh$/ { print repl; next }
    { print }
  ' "$toml" > "$toml.tmp" && cat "$toml.tmp" > "$toml" && rm -f "$toml.tmp"
  # cat > (not mv) so a stow-managed symlink is written through, not replaced
}

case "$action" in
  save)
    [ -z "$name" ] && { echo "usage: display.sh save <name>"; exit 1; }
    cmd=$(displayplacer list | grep '^displayplacer ')
    if [ -z "$cmd" ]; then
      echo "displayplacer produced no arrangement — is anything connected?" >&2
      exit 1
    fi
    printf '%s\n' "$cmd" > "$PROFILE_DIR/$name.displayplacer"
    echo "Saved profile '$name'."
    echo
    echo "displayplacer arrangement:"
    echo "  $cmd"
    echo
    echo "AeroSpace monitor names right now (use these in the assignment block):"
    aerospace list-monitors
    ;;

  apply)
    [ -z "$name" ] && { echo "usage: display.sh apply <name>"; exit 1; }
    f="$PROFILE_DIR/$name.displayplacer"
    if [ ! -f "$f" ]; then
      # Not captured yet — flag it on the widget and bail.
      sketchybar --set display label="$name (uncaptured)" label.color="$RED"
      echo "Profile '$name' not captured yet. Plug in that setup and run:" >&2
      echo "  $HOME/.config/sketchybar/plugins/display.sh save $name" >&2
      exit 1
    fi
    eval "$(cat "$f")"
    printf '%s\n' "$name" > "$STATE"

    # .current is written first: both sync_gaps and the reloaded sketchybarrc
    # read it to pick their preset.
    sync_gaps
    aerospace reload-config
    sketchybar --reload
    sleep 0.4          # let the reloaded config finish adding items
    "$0" update
    sketchybar --set display popup.drawing=off
    ;;

  sync)
    sync_gaps
    aerospace reload-config
    sketchybar --reload
    sleep 0.4
    "$0" update
    echo "Re-applied sizing for profile '$(cat "$STATE" 2>/dev/null)'."
    ;;

  update)
    cur=$(cat "$STATE" 2>/dev/null)
    [ -z "$cur" ] && cur="—"
    sketchybar --set display label="$cur" label.color="$LABEL_COLOR"
    ;;

  *)
    echo "usage: display.sh {save|apply|sync|update} [name]" >&2
    exit 1
    ;;
esac
